# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

fastlane_version "2.14.2"
default_platform :ios
skip_docs

# Fastfile actions accept additional configuration, but
# don't worry, fastlane will prompt you for required
# info which you can add here later

lane :beta do
    # check that repo is clean
    ensure_git_status_clean

    # increment build number
    increment_build_number

    # build your iOS app
    gym(
        clean: true,
        export_method: "app-store",
        output_directory: "build",
        scheme: "Dookie",
        silent: true,
        workspace: "Dookie.xcworkspace"
    )

    # upload to Test Flight
    pilot(
        ipa: "build/Dookie.ipa",
        changelog: changelog_from_git_commits(pretty: "• %s")
    )

    # clean up folder
    clean_build_artifacts

    # version controll
    commit_version_bump
    add_git_tag
    push_to_git_remote
end
